use serde::{Deserialize, Serialize};

// ─── Epic ────────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum EpicStatus {
    Draft,
    Speccing,
    Decomposing,
    Planning,
    Ready,
    Executing,
    Verifying,
    Completed,
    Failed,
    Paused,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuestionOption {
    pub label: String,
    pub description: String,
    /// Single hex color code for simple color questions (e.g. "#8B5CF6")
    #[serde(default)]
    pub color: Option<String>,
    /// Full color palette for palette questions — array of {name, hex} pairs
    #[serde(default)]
    pub palette: Option<Vec<PaletteColor>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaletteColor {
    pub name: String,
    pub hex: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ClarifyingQA {
    pub question: String,
    pub answer: String,
    pub asked_at: String,
    #[serde(default)]
    pub context: String,
    /// Selectable options generated by the AI
    #[serde(default)]
    pub options: Vec<QuestionOption>,
    /// Whether multiple options can be selected
    #[serde(default)]
    pub multi_select: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Epic {
    pub id: String,
    pub title: String,
    pub objective: String,
    pub status: EpicStatus,
    /// Interactive planning step: draft|scouting|clarifying|specs_review|tickets_review|phases_review|ready
    #[serde(default = "default_planning_step")]
    pub planning_step: String,
    pub clarifying_questions: Vec<ClarifyingQA>,
    pub spec_ids: Vec<String>,
    pub ticket_ids: Vec<String>,
    pub model_config: super::config::ModelConfig,
    pub created_at: String,
    pub updated_at: String,
    pub target_dir: String,
    pub total_estimated_phases: u32,
    pub completed_phases: u32,
    pub total_cost_usd: f64,
    /// Cached codebase analysis from the scout
    #[serde(default)]
    pub codebase_context: Option<String>,
    /// Whether a planning step is currently running (prevents double-starts)
    #[serde(default)]
    pub planning_active: bool,
    /// Which clarification round we're on (1=experience, 2=concept, 3=design, 4+=deep dive)
    #[serde(default = "default_clarification_round")]
    pub clarification_round: u32,
}

fn default_clarification_round() -> u32 {
    1
}

fn default_planning_step() -> String {
    "draft".to_string()
}

// ─── Ticket ──────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum TicketStatus {
    Todo,
    Planning,
    Ready,
    InProgress,
    Verifying,
    Done,
    Failed,
    Blocked,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum Complexity {
    Trivial,
    Small,
    Medium,
    Large,
    Epic,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TicketScope {
    pub primary_files: Vec<String>,
    pub reference_files: Vec<String>,
    pub directories: Vec<String>,
    pub technologies: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Ticket {
    pub id: String,
    pub epic_id: String,
    pub title: String,
    pub description: String,
    pub acceptance_criteria: Vec<String>,
    pub status: TicketStatus,
    pub priority: u32,
    pub dependencies: Vec<String>,
    pub scope: TicketScope,
    pub phase_ids: Vec<String>,
    pub estimated_complexity: Complexity,
    pub cost_usd: f64,
    pub created_at: String,
    pub updated_at: String,
}

// ─── Phase ───────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum PhaseStatus {
    Planned,
    Executing,
    Verifying,
    Passed,
    Failed,
    Remediating,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlanStep {
    pub order: u32,
    pub description: String,
    pub file_targets: Vec<String>,
    pub tool: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FileOperation {
    pub path: String,
    pub description: String,
    pub references: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PhasePlan {
    pub objective: String,
    pub steps: Vec<PlanStep>,
    pub files_to_create: Vec<FileOperation>,
    pub files_to_modify: Vec<FileOperation>,
    pub files_to_delete: Vec<String>,
    pub test_strategy: String,
    pub rollback_strategy: String,
    pub context_files: Vec<String>,
    pub reasoning: String,
    pub mermaid_diagram: Option<String>,
    /// Spec file paths the implementer should read for full details
    #[serde(default)]
    pub reference_docs: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Phase {
    pub id: String,
    pub ticket_id: String,
    pub epic_id: String,
    pub order: u32,
    pub title: String,
    pub description: String,
    pub plan: PhasePlan,
    pub status: PhaseStatus,
    pub execution: Option<super::execution::PhaseExecution>,
    pub verification: Option<super::verification::PhaseVerification>,
    pub remediation_attempts: u32,
    pub max_remediation_attempts: u32,
    pub cost_usd: f64,
    pub duration_ms: u64,
    pub created_at: String,
    pub updated_at: String,
}

// ─── Spec (Artifact) ────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum SpecType {
    Prd,
    TechSpec,
    Architecture,
    ApiSpec,
    DesignSpec,
    Custom,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MermaidDiagram {
    pub id: String,
    pub title: String,
    pub diagram_type: String,
    pub content: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Spec {
    pub id: String,
    pub epic_id: String,
    pub spec_type: SpecType,
    pub title: String,
    pub content: String,
    pub mermaid_diagrams: Vec<MermaidDiagram>,
    pub version: u32,
    pub created_at: String,
    pub updated_at: String,
}
